groups:
  - name: docker_swarm_alerts
    rules:
      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "The service {{ $labels.job }} on instance {{ $labels.instance }} has been down for more than 30 seconds."

      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage on {{ $labels.instance }} is above {{ printf \"%.2f\" $value }}% for more than 5 minutes."

      # High memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage on {{ $labels.instance }} is above {{ printf \"%.2f\" $value }}% for more than 5 minutes."

      # Low disk space
      - alert: LowDiskSpace
        expr: node_filesystem_avail_bytes{fstype!="tmpfs", mountpoint!~"/(boot|proc|sys|run)"} / node_filesystem_size_bytes{fstype!="tmpfs", mountpoint!~"/(boot|proc|sys|run)"} * 100 < 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Filesystem {{ $labels.mountpoint }} on {{ $labels.instance }} has less than 10% available space."

      # Container restarting frequently
      - alert: ContainerHighRestartRate
        expr: rate(container_start_time_seconds[10m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container restarting frequently"
          description: |
            The container {{ $labels.name }} from service {{ $labels.container_label_com_docker_swarm_service_name }}
            (project {{ $labels.container_label_com_docker_stack_namespace }}) is restarting frequently.

      # High memory usage by container
      - alert: ContainerHighMemoryUsage
        expr: container_spec_memory_limit_bytes > 0
              and (container_memory_usage_bytes / clamp_min(container_spec_memory_limit_bytes, 1) * 100 > 90)
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in container"
          description: |
            The container {{ $labels.name }} from service {{ $labels.container_label_com_docker_swarm_service_name }}
            (project {{ $labels.container_label_com_docker_stack_namespace }}) on {{ $labels.instance }}
            is using {{ printf "%.2f" $value }}% of its memory limit.
