server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container_name

      - source_labels: [container_name]
        regex: '([^_]+)_.*'
        target_label: stack

      - source_labels: [container_name]
        regex: '[^_]+_([^\.]+)\..*'
        target_label: service

      - source_labels: [container_name]
        regex: '(.*)'
        target_label: task

      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      - source_labels: [__meta_docker_container_label_com_docker_swarm_node_id]
        target_label: node_id

      - source_labels: [__meta_docker_container_network_mode]
        target_label: network_mode

      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream