server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 1048576
    batchwait: 1s
    timeout: 10s
    backoff_config:
      min_period: 500ms
      max_period: 5m
      max_retries: 10

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container_name

      - source_labels: [__meta_docker_container_label_com_docker_swarm_stack_namespace]
        target_label: stack

      - source_labels: [__meta_docker_container_label_com_docker_swarm_service_name]
        target_label: service_name

      - source_labels: [__meta_docker_container_label_com_docker_swarm_task_name]
        target_label: task_name

      - source_labels: [__meta_docker_container_label_com_docker_swarm_node_id]
        target_label: node_id

      - source_labels: [__meta_docker_container_label_com_docker_swarm_task_slot]
        target_label: replica

    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
            service: service

      - labels:
          level:
          service

      - timestamp:
          source: timestamp
          format: RFC3339Nano
          fallback_formats:
            - RFC3339
            - '2006-01-02T15:04:05.999999999Z07:00'

limits_config:
  readline_rate: 10000
  readline_burst: 20000
